name: "benchmarks"

on:
  pull_request: ~
  push: ~

jobs:
  unit-tests:
    name: "benchmarks"

    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        php-version:
          - "8.0"
        operating-system:
          - "ubuntu-latest"

    steps:
      - name: "checkout"
        uses: "actions/checkout@v2"

      - name: "installing PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          ini-values: memory_limit=-1
          tools: composer:v2, cs2pr
          extensions: bcmath, mbstring, intl, sodium, json, opcache, apcu
          coverage: none

      - name: "installing dependencies"
        run: "composer install --no-interaction --no-progress"

      - name: "running phpbench ( raw )"
        run: php vendor/bin/phpbench run --report=default --group raw
      
      - name: "running phpbench ( cached )"
        run: php vendor/bin/phpbench run --report=default --group cached
      
      - name: "running phpbench ( instance )"
        run: php vendor/bin/phpbench run --report=default --group instance

      - name: "running quick benchmarks"
        run: php scripts/quick-benchmark.php
